#!/bin/sh

# install.sh – установка скрипта проверки WAN IP на OpenWRT
# Использование: curl -fsSL https://raw.githubusercontent.com/Erridium/openwrt-wan-ip-check/main/install.sh | sh

set -e

REPO="Erridium/openwrt-wan-ip-check"
BRANCH="main"
BASE_URL="https://raw.githubusercontent.com/$REPO/$BRANCH"

echo "Установка скрипта проверки WAN IP для OpenWRT"
echo "----------------------------------------------"

# Проверка наличия curl
if ! command -v curl >/dev/null 2>&1; then
    echo "curl не найден. Устанавливаем..."
    opkg update && opkg install curl
fi

# Скачиваем основной скрипт
echo "Скачивание основного скрипта..."
curl -fsSL -o /usr/bin/check_wan_ip.sh "$BASE_URL/check_wan_ip.sh"
chmod +x /usr/bin/check_wan_ip.sh

echo ""
echo "Настройка параметров (Enter - оставить значение по умолчанию)"

# Перенаправляем весь последующий ввод на терминал,
# чтобы read читал с клавиатуры, а не из пайпа.
exec < /dev/tty

# WAN interface
DEFAULT_WAN="wan"
echo -n "Имя WAN интерфейса [$DEFAULT_WAN]: "
read WAN_INTERFACE
if [ -z "$WAN_INTERFACE" ]; then
    WAN_INTERFACE="$DEFAULT_WAN"
fi

# Target network
DEFAULT_TARGET="79.105.0.0/16"
echo -n "Желаемая сеть (CIDR) [$DEFAULT_TARGET]: "
read TARGET_NETWORK
if [ -z "$TARGET_NETWORK" ]; then
    TARGET_NETWORK="$DEFAULT_TARGET"
fi

# Unwanted network (optional)
DEFAULT_UNWANTED="100.64.0.0/10"
echo -n "Нежелательная сеть (CIDR) для логирования (Enter - пропустить) [$DEFAULT_UNWANTED]: "
read UNWANTED_NETWORK
if [ -z "$UNWANTED_NETWORK" ]; then
    UNWANTED_NETWORK=""
fi

# Check interval
DEFAULT_INTERVAL=60
echo -n "Интервал проверки (секунд) [$DEFAULT_INTERVAL]: "
read CHECK_INTERVAL
if [ -z "$CHECK_INTERVAL" ]; then
    CHECK_INTERVAL="$DEFAULT_INTERVAL"
fi

# Restart delay
DEFAULT_DELAY=60
echo -n "Задержка после перезапуска интерфейса (секунд) [$DEFAULT_DELAY]: "
read RESTART_DELAY
if [ -z "$RESTART_DELAY" ]; then
    RESTART_DELAY="$DEFAULT_DELAY"
fi

# Log file
DEFAULT_LOG="/var/log/wan_ip_check.log"
echo -n "Файл лога [$DEFAULT_LOG]: "
read LOG_FILE
if [ -z "$LOG_FILE" ]; then
    LOG_FILE="$DEFAULT_LOG"
fi

# Создание конфигурационного файла
CONFIG_FILE="/etc/wan-ip-check.conf"
echo "Создание конфигурационного файла $CONFIG_FILE..."
cat > "$CONFIG_FILE" << EOF
# Configuration for WAN IP check script
# Generated by install.sh on $(date)

WAN_INTERFACE="$WAN_INTERFACE"
TARGET_NETWORK="$TARGET_NETWORK"
UNWANTED_NETWORK="$UNWANTED_NETWORK"
CHECK_INTERVAL="$CHECK_INTERVAL"
RESTART_DELAY="$RESTART_DELAY"
LOG_FILE="$LOG_FILE"
EOF

echo "Конфигурация сохранена."

# Настройка автозапуска через rc.local
echo "Настройка автозапуска через /etc/rc.local..."
# Удаляем предыдущие строки с вызовом скрипта
sed -i '/check_wan_ip.sh/d' /etc/rc.local
# Добавляем запуск перед exit 0
sed -i "/exit 0/i /usr/bin/check_wan_ip.sh \&" /etc/rc.local

# Запуск скрипта
echo "Запуск скрипта..."
/usr/bin/check_wan_ip.sh &

echo "Установка завершена!"
echo "Логи можно смотреть командой: logread | grep wan-ip-check"
echo "Или tail -f $LOG_FILE"
echo "Для изменения параметров отредактируйте $CONFIG_FILE и перезапустите скрипт."
