#!/bin/sh

# install.sh – установка скрипта проверки WAN IP на OpenWRT с интерактивной настройкой
# Использование: curl -fsSL https://raw.githubusercontent.com/Erridium/openwrt-wan-ip-check/main/install.sh | sh

set -e

REPO="Erridium/openwrt-wan-ip-check"
BRANCH="main"
BASE_URL="https://raw.githubusercontent.com/$REPO/$BRANCH"

# Цвета (используем прямые escape-последовательности в printf)
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Проверка, что вывод в терминал, иначе не используем цвета
if [ ! -t 1 ]; then
    GREEN=''; YELLOW=''; RED=''; NC=''
fi

printf "${GREEN}%s${NC}\n" "Установка скрипта проверки WAN IP для OpenWRT"
printf "%s\n" "------------------------------------------------"

# Проверка наличия curl
if ! command -v curl >/dev/null 2>&1; then
    printf "${RED}%s${NC}\n" "curl не найден. Устанавливаем..."
    opkg update && opkg install curl
fi

# Скачиваем основной скрипт
printf "${YELLOW}%s${NC}\n" "Скачивание основного скрипта..."
curl -fsSL -o /usr/bin/check_wan_ip.sh "$BASE_URL/check_wan_ip.sh"
chmod +x /usr/bin/check_wan_ip.sh

# Интерактивный ввод параметров
printf "\n"
printf "${GREEN}%s${NC}\n" "Настройка параметров (Enter - оставить значение по умолчанию)"

# WAN interface
DEFAULT_WAN="wan"
printf "Имя WAN интерфейса [%s]: " "$DEFAULT_WAN"
read WAN_INTERFACE
if [ -z "$WAN_INTERFACE" ]; then
    WAN_INTERFACE="$DEFAULT_WAN"
fi

# Target network
DEFAULT_TARGET="79.105.0.0/16"
printf "Желаемая сеть (CIDR) [%s]: " "$DEFAULT_TARGET"
read TARGET_NETWORK
if [ -z "$TARGET_NETWORK" ]; then
    TARGET_NETWORK="$DEFAULT_TARGET"
fi

# Unwanted network (optional)
DEFAULT_UNWANTED="100.64.0.0/10"
printf "Нежелательная сеть (CIDR) для логирования, Enter если не нужна [%s]: " "$DEFAULT_UNWANTED"
read UNWANTED_NETWORK
# Если пользователь ввел пустую строку, то оставляем пустой (не подставляем дефолт)
# Дефолт подставляем только если ввели не пустую строку? Нет, в вопросе сказано "Enter если не нужна" - значит, если ввели пустую, то оставляем пустую.
# Поэтому здесь не присваиваем дефолт. Если нужно чтобы дефолт был, а пустая строка означала "не нужна" - это уже реализовано.

# Check interval
DEFAULT_INTERVAL=60
printf "Интервал проверки (секунд) [%s]: " "$DEFAULT_INTERVAL"
read CHECK_INTERVAL
if [ -z "$CHECK_INTERVAL" ]; then
    CHECK_INTERVAL="$DEFAULT_INTERVAL"
fi

# Restart delay
DEFAULT_DELAY=60
printf "Задержка после перезапуска интерфейса (секунд) [%s]: " "$DEFAULT_DELAY"
read RESTART_DELAY
if [ -z "$RESTART_DELAY" ]; then
    RESTART_DELAY="$DEFAULT_DELAY"
fi

# Log file
DEFAULT_LOG="/var/log/wan_ip_check.log"
printf "Файл лога [%s]: " "$DEFAULT_LOG"
read LOG_FILE
if [ -z "$LOG_FILE" ]; then
    LOG_FILE="$DEFAULT_LOG"
fi

# Создание конфигурационного файла
CONFIG_FILE="/etc/wan-ip-check.conf"
printf "${YELLOW}%s${NC}\n" "Создание конфигурационного файла $CONFIG_FILE..."
cat > "$CONFIG_FILE" << EOF
# Configuration for WAN IP check script
# Generated by install.sh on $(date)

WAN_INTERFACE="$WAN_INTERFACE"
TARGET_NETWORK="$TARGET_NETWORK"
UNWANTED_NETWORK="$UNWANTED_NETWORK"
CHECK_INTERVAL="$CHECK_INTERVAL"
RESTART_DELAY="$RESTART_DELAY"
LOG_FILE="$LOG_FILE"
EOF

printf "${GREEN}%s${NC}\n" "Конфигурация сохранена."

# Настройка автозапуска через rc.local
printf "${YELLOW}%s${NC}\n" "Настройка автозапуска через /etc/rc.local..."
# Удаляем предыдущие строки с вызовом скрипта
sed -i '/check_wan_ip.sh/d' /etc/rc.local
# Добавляем запуск перед exit 0
sed -i '/exit 0/i /usr/bin/check_wan_ip.sh \&' /etc/rc.local

# Запуск скрипта
printf "${YELLOW}%s${NC}\n" "Запуск скрипта..."
/usr/bin/check_wan_ip.sh &

printf "${GREEN}%s${NC}\n" "Установка завершена!"
printf "%s\n" "Логи можно смотреть командой: logread | grep wan-ip-check"
printf "%s\n" "Или tail -f $LOG_FILE"
printf "%s\n" "Для изменения параметров отредактируйте $CONFIG_FILE и перезапустите скрипт."
